#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# Portfolio setup wizard (Phase 0b PR 4, ticket #13). Generated with /wizard; the library above
# is .agents/skills/wizard/template.sh unchanged. Runbook: docs/runbooks/setup-wizard.md.
# Dashboard paths verified against the Vercel docs on 2026-10-10 (deployment-checks,
# project-configuration/git-configuration); GitHub paths against the repository the same day.
#
# This wizard writes exactly one value, ANTHROPIC_API_KEY, and only as a GitHub Actions secret
# (ci.yml, job ai-review). It never writes a dotenv file: ENV_FILE points at /dev/null, which is
# not a regular file, so the library's re-run defaults never read one either (CLAUDE.md Boundaries).
# Every other stage is a dashboard action the Owner confirms; nothing here runs on an agent.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=/dev/null
REPO="cov1983/portfolio"
RULESET_ID=24534327 # the `main` ruleset: gh api repos/$REPO/rulesets
# CI job ids that gate production (ci.yml header). Stages 2, 7 and 8 share this list.
CHECKS=(lint test build e2e perf sast deps gitleaks spec-freeze)

TOTAL_STAGES=8

banner "Portfolio setup: Vercel, CI review key, Renovate, CodeQL, domain, ruleset"

# ── 1. Vercel project ─────────────────────────────────────────────────────
stage "Vercel: import the repository"
say "Hosting is Vercel through its GitHub integration (docs/adr/0006-hosting-vercel.md)."
say "Every build setting is read from vercel.json; the dashboard only needs the project to exist."
open_url "https://vercel.com/new"
step "Sign in, choose 'Import Git Repository' and pick $REPO."
step "When GitHub asks where to install the Vercel app, grant access to this repository only."
step "Leave the detected settings alone (Vite, pnpm install --frozen-lockfile, pnpm exec vite build, dist): they come from vercel.json. Click Deploy."
pause "Press Enter once the first deployment has finished."
step "Open the project → Settings → Environments → Production and confirm Branch Tracking is 'main'."
step "Open the pull request for this branch on GitHub: a 'Preview' deployment comment from Vercel should be there."
if ! confirm "Is the production branch 'main' and did the preview appear on the pull request?"; then
  SKIPPED+=("Vercel: production branch tracking = main, preview on the pull request")
fi

# ── 2. Deployment Checks ──────────────────────────────────────────────────
stage "Vercel: Deployment Checks hold production until CI is green"
say "A production deployment is built on every merge to main but is only aliased to the domain"
say "once the selected GitHub checks pass for that commit. Checks match CI job names."
step "Project → Settings → Build and Deployment → Deployment Checks → Add Checks → GitHub."
step "Select these ${#CHECKS[@]} checks (search by name):"
for c in "${CHECKS[@]}"; do note "    $c"; done
note "Leave ai-review out: it never blocks (its findings are a Definition of Done item)."
pause "Press Enter once all ${#CHECKS[@]} checks are listed as required."
if ! confirm "Are the ${#CHECKS[@]} checks listed under Deployment Checks?"; then
  SKIPPED+=("Vercel Deployment Checks: ${CHECKS[*]}")
fi

# ── 3. ANTHROPIC_API_KEY ──────────────────────────────────────────────────
stage "GitHub secret: ANTHROPIC_API_KEY for the independent review"
say "The ai-review CI job (anthropics/claude-code-action, read-only tools) posts one tracking"
say "comment per pull request. Until the key exists the job is skipped with a notice."
open_url "https://console.anthropic.com/settings/keys"
step "Create a key named 'portfolio-ci-review'. Copy it: it is shown once."
note "The key is used only by that job, which cannot write files or push; spend is a few cents per review."
ask_secret ANTHROPIC_API_KEY "Paste the key (hidden):"
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  set_secret ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
else
  SKIPPED+=("GitHub secret ANTHROPIC_API_KEY (gh secret set ANTHROPIC_API_KEY)")
  warn "no key entered; the ai-review job stays skipped"
fi
unset ANTHROPIC_API_KEY

# ── 4. Renovate ───────────────────────────────────────────────────────────
stage "Renovate: install the app and allow auto-merge"
say "renovate.json (ADR 0007) groups patch updates and merges them once every required check is green."
open_url "https://github.com/apps/renovate"
step "Install (or Configure) → select 'Only select repositories' → $REPO → Install."
open_url "https://github.com/$REPO/settings"
step "Under 'Pull Requests' tick 'Allow auto-merge', then Save."
pause "Press Enter when both are done."
step "Within a few minutes Renovate opens an issue titled 'Dependency Dashboard' on the repository."
if ! confirm "Is 'Allow auto-merge' on and the Dependency Dashboard issue open (or expected)?"; then
  SKIPPED+=("Renovate app installed; repository setting 'Allow auto-merge'")
fi

# ── 5. CodeQL and the dependency graph ────────────────────────────────────
stage "GitHub: CodeQL advanced setup and the dependency graph"
say "The sast job runs CodeQL from ci.yml and uploads results; GitHub's 'default setup' blocks"
say "those uploads, so it must be off. The deps job needs the dependency graph."
open_url "https://github.com/$REPO/settings/security_analysis"
step "Code scanning → CodeQL analysis: if it says 'Default', switch it to 'Advanced' (the workflow is already committed)."
step "Dependency graph: must be enabled (it was on 2026-10-10; just confirm)."
pause "Press Enter when both are confirmed."
step "After the next CI run on main, Security → Code scanning lists the results."
if ! confirm "Is CodeQL on advanced setup and the dependency graph enabled?"; then
  SKIPPED+=("GitHub: CodeQL default setup off, dependency graph on")
fi

# ── 6. Domain ─────────────────────────────────────────────────────────────
stage "Domain: assign the Owner's domain and point its DNS at Vercel"
say "You already own the domain; its DNS zone is managed at Infomaniak. Vercel does not need to"
say "become the registrar or the nameserver: two records in the existing zone are enough."
open_url "https://vercel.com/dashboard"
step "Project → Settings → Domains → Add → enter the domain (and 'www.' if you want it) → Add."
step "Vercel now shows the records it expects: an A record for the apex and a CNAME for www, with the exact values. Keep that page open."
open_url "https://manager.infomaniak.com/"
step "Web & Domains → the domain → DNS zone (the menu names may differ slightly): add the A record and the CNAME exactly as Vercel shows them; delete any old A/AAAA/CNAME on the same names."
note "Propagation takes minutes to an hour. Vercel's Domains page flips to 'Valid Configuration' and issues the certificate by itself."
pause "Press Enter once Vercel shows the domain as valid (or once the records are saved and you are waiting)."
if ! confirm "Is the domain assigned to the project with its DNS records saved at Infomaniak?"; then
  SKIPPED+=("Domain assigned to the Vercel project; A and CNAME records in the Infomaniak zone")
  printf '  %s%s%s\n' "$RED" "Fallback only: buying a domain is irreversible and costs money every year." "$RESET"
  if confirm "Do you want to buy a new domain through Vercel instead?"; then
    open_url "https://vercel.com/domains"
    step "Search the name, check the yearly price, buy it, then assign it under Project → Settings → Domains. DNS is managed by Vercel in that case."
    pause "Press Enter when the bought domain is assigned (or to skip)."
  fi
fi

# ── 7. Required checks on main ────────────────────────────────────────────
stage "GitHub ruleset: every gate becomes a required check on main"
say "Today the main ruleset requires lint, test and gitleaks. The other jobs exist since Phase 0b PR 3"
say "and have run green; they become required now so Renovate's auto-merge waits for all of them."
open_url "https://github.com/$REPO/settings/rules/$RULESET_ID"
step "Under 'Require status checks to pass' add the missing ones so the list reads:"
for c in "${CHECKS[@]}"; do note "    $c"; done
note "Not ai-review. Keep 'Require branches to be up to date' as it is. Save changes."
pause "Press Enter once the ruleset is saved."

# ── 8. Smoke ──────────────────────────────────────────────────────────────
stage "Smoke: what gh can verify from here"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh secret list --repo "$REPO" 2>/dev/null | grep -q '^ANTHROPIC_API_KEY'; then
    printf '  %s✓%s secret ANTHROPIC_API_KEY is stored\n' "$GREEN" "$RESET"
  else
    warn "secret ANTHROPIC_API_KEY not found"
    SKIPPED+=("GitHub secret ANTHROPIC_API_KEY")
  fi
  if [[ "$(gh api "repos/$REPO" --jq .allow_auto_merge 2>/dev/null)" == "true" ]]; then
    printf '  %s✓%s repository allows auto-merge\n' "$GREEN" "$RESET"
  else
    warn "repository setting 'Allow auto-merge' is off"
    SKIPPED+=("Repository setting 'Allow auto-merge' (Renovate)")
  fi
  required="$(gh api "repos/$REPO/rulesets/$RULESET_ID" \
    --jq '.rules[] | select(.type=="required_status_checks") | .parameters.required_status_checks[].context' 2>/dev/null || true)"
  missing=()
  for c in "${CHECKS[@]}"; do
    grep -qx "$c" <<<"$required" || missing+=("$c")
  done
  if (( ${#missing[@]} == 0 )); then
    printf '  %s✓%s ruleset main requires all %s checks\n' "$GREEN" "$RESET" "${#CHECKS[@]}"
  else
    warn "ruleset main is missing required checks: ${missing[*]}"
    SKIPPED+=("Ruleset main required checks: ${missing[*]}")
  fi
else
  warn "gh is not authenticated; nothing verified from here"
  SKIPPED+=("Smoke checks (run: gh auth login, then re-run this wizard)")
fi
note "Not verifiable from here: the Vercel project, Deployment Checks and the domain. Check them in the dashboard."
pause "Press Enter for the summary."

finish
